// <auto-generated />
using System;
using Edu.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edu.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edu.Domain.Entities.Admin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoStorageKey")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("it");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Edu.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MeetUrl")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RequestedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SlotId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameIt")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageKey")
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Curricula");
                });

            modelBuilder.Entity("Edu.Domain.Entities.FileResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileType")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("OnlineCourseLessonId")
                        .HasColumnType("integer");

                    b.Property<int?>("PrivateLessonId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReactiveCourseLessonId")
                        .HasColumnType("integer");

                    b.Property<int?>("SchoolLessonId")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OnlineCourseLessonId");

                    b.HasIndex("PrivateLessonId");

                    b.HasIndex("ReactiveCourseLessonId");

                    b.HasIndex("SchoolLessonId");

                    b.HasIndex("StorageKey")
                        .HasDatabaseName("IX_FileResource_StorageKey");

                    b.ToTable("FileResources");
                });

            modelBuilder.Entity("Edu.Domain.Entities.FooterContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("FooterContacts");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HeroSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionIt")
                        .HasColumnType("text");

                    b.Property<string>("ImageStorageKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Placement")
                        .HasColumnType("integer");

                    b.Property<string>("TitleAr")
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text");

                    b.Property<string>("TitleIt")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HeroSections");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HomeSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageStorageKey")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HomeSections");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HomeSectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HomeSectionId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageStorageKey")
                        .HasColumnType("text");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("HomeSectionId");

                    b.ToTable("HomeSectionItems");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HomeSectionItemTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HomeSectionItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("HomeSectionItemId", "Culture")
                        .IsUnique();

                    b.ToTable("HomeSectionItemTranslations");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HomeSectionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HomeSectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("HomeSectionId", "Culture")
                        .IsUnique();

                    b.ToTable("HomeSectionTranslations");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameIt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("IntroductionVideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("OnlineCourses");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineCourseLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MeetUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OnlineCourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("OnlineCourseMonthId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("RecordedVideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ScheduledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OnlineCourseId");

                    b.HasIndex("OnlineCourseMonthId");

                    b.ToTable("OnlineCourseLessons");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineCourseMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsReadyForPayment")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MonthEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MonthIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MonthStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OnlineCourseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OnlineCourseId", "MonthIndex")
                        .IsUnique();

                    b.ToTable("OnlineCourseMonths");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("OnlineCourseId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("OnlineCourseId", "StudentId")
                        .IsUnique();

                    b.ToTable("OnlineEnrollments");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineEnrollmentMonthPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OnlineCourseMonthId")
                        .HasColumnType("integer");

                    b.Property<int>("OnlineEnrollmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OnlineCourseMonthId");

                    b.HasIndex("OnlineEnrollmentId", "OnlineCourseMonthId");

                    b.ToTable("OnlineEnrollmentMonthPayments");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PrivateCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverImageKey")
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsForChildren")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublishRequested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TeacherId");

                    b.ToTable("PrivateCourses");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PrivateLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PrivateCourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("PrivateModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.Property<string>("YouTubeVideoId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PrivateCourseId");

                    b.HasIndex("PrivateModuleId");

                    b.ToTable("PrivateLessons");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PrivateModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PrivateCourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("PrivateCourseId");

                    b.ToTable("PrivateModules");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PurchaseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrivateCourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrivateCourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("CoverImageKey")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IntroVideoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("ReactiveCourses");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveCourseLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MeetUrl")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ReactiveCourseMonthId")
                        .HasColumnType("integer");

                    b.Property<string>("RecordedVideoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReactiveCourseMonthId");

                    b.ToTable("ReactiveCourseLessons");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveCourseMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsReadyForPayment")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MonthEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MonthIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MonthStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReactiveCourseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReactiveCourseId");

                    b.ToTable("ReactiveCourseMonths");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("ReactiveCourseId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ReactiveCourseId", "StudentId")
                        .IsUnique();

                    b.ToTable("ReactiveEnrollments");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveEnrollmentMonthPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<int>("ReactiveCourseMonthId")
                        .HasColumnType("integer");

                    b.Property<int>("ReactiveEnrollmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReactiveCourseMonthId");

                    b.HasIndex("ReactiveEnrollmentId", "ReactiveCourseMonthId");

                    b.ToTable("ReactiveEnrollmentMonthPayments");
                });

            modelBuilder.Entity("Edu.Domain.Entities.SchoolLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.Property<string>("YouTubeVideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("ModuleId");

                    b.ToTable("SchoolLessons");
                });

            modelBuilder.Entity("Edu.Domain.Entities.SchoolModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("SchoolModules");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StartUtc");

                    b.HasIndex("TeacherId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Edu.Domain.Entities.SocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("SocialLinks");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GuardianPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Edu.Domain.Entities.StudentCurriculum", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "CurriculumId");

                    b.HasIndex("CurriculumId");

                    b.ToTable("StudentCurricula");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CVStorageKey")
                        .HasColumnType("text");

                    b.Property<string>("CVUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IntroVideoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ShortBio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Edu.Domain.Entities.Admin", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ApplicationUser", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("Edu.Domain.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Edu.Domain.Entities.Slot", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Edu.Domain.Entities.Student", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentId");

                    b.HasOne("Edu.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Bookings")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Slot");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Curriculum", b =>
                {
                    b.HasOne("Edu.Domain.Entities.Level", "Level")
                        .WithMany("Curricula")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Edu.Domain.Entities.FileResource", b =>
                {
                    b.HasOne("Edu.Domain.Entities.OnlineCourseLesson", "OnlineCourseLesson")
                        .WithMany("Files")
                        .HasForeignKey("OnlineCourseLessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_FileResource_OnlineCourseLesson");

                    b.HasOne("Edu.Domain.Entities.PrivateLesson", "PrivateLesson")
                        .WithMany("Files")
                        .HasForeignKey("PrivateLessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_FileResource_PrivateLesson");

                    b.HasOne("Edu.Domain.Entities.ReactiveCourseLesson", "ReactiveCourseLesson")
                        .WithMany("Files")
                        .HasForeignKey("ReactiveCourseLessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_FileResource_ReactiveCourseLesson");

                    b.HasOne("Edu.Domain.Entities.SchoolLesson", "SchoolLesson")
                        .WithMany("Files")
                        .HasForeignKey("SchoolLessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_FileResource_SchoolLesson");

                    b.Navigation("OnlineCourseLesson");

                    b.Navigation("PrivateLesson");

                    b.Navigation("ReactiveCourseLesson");

                    b.Navigation("SchoolLesson");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HomeSectionItem", b =>
                {
                    b.HasOne("Edu.Domain.Entities.HomeSection", "HomeSection")
                        .WithMany("Items")
                        .HasForeignKey("HomeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeSection");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HomeSectionItemTranslation", b =>
                {
                    b.HasOne("Edu.Domain.Entities.HomeSectionItem", "HomeSectionItem")
                        .WithMany("Translations")
                        .HasForeignKey("HomeSectionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeSectionItem");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HomeSectionTranslation", b =>
                {
                    b.HasOne("Edu.Domain.Entities.HomeSection", "HomeSection")
                        .WithMany("Translations")
                        .HasForeignKey("HomeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeSection");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineCourse", b =>
                {
                    b.HasOne("Edu.Domain.Entities.Level", null)
                        .WithMany("OnlineCourses")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineCourseLesson", b =>
                {
                    b.HasOne("Edu.Domain.Entities.OnlineCourse", "OnlineCourse")
                        .WithMany("Lessons")
                        .HasForeignKey("OnlineCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.OnlineCourseMonth", "OnlineCourseMonth")
                        .WithMany("Lessons")
                        .HasForeignKey("OnlineCourseMonthId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("OnlineCourse");

                    b.Navigation("OnlineCourseMonth");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineCourseMonth", b =>
                {
                    b.HasOne("Edu.Domain.Entities.OnlineCourse", "OnlineCourse")
                        .WithMany("Months")
                        .HasForeignKey("OnlineCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnlineCourse");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineEnrollment", b =>
                {
                    b.HasOne("Edu.Domain.Entities.OnlineCourse", "OnlineCourse")
                        .WithMany("Enrollments")
                        .HasForeignKey("OnlineCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("OnlineCourse");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineEnrollmentMonthPayment", b =>
                {
                    b.HasOne("Edu.Domain.Entities.OnlineCourseMonth", "OnlineCourseMonth")
                        .WithMany("MonthPayments")
                        .HasForeignKey("OnlineCourseMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.OnlineEnrollment", "OnlineEnrollment")
                        .WithMany("MonthPayments")
                        .HasForeignKey("OnlineEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OnlineCourseMonth");

                    b.Navigation("OnlineEnrollment");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PrivateCourse", b =>
                {
                    b.HasOne("Edu.Domain.Entities.Category", "Category")
                        .WithMany("PrivateCourses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.Teacher", "Teacher")
                        .WithMany("PrivateCourses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Category");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PrivateLesson", b =>
                {
                    b.HasOne("Edu.Domain.Entities.PrivateCourse", "PrivateCourse")
                        .WithMany("PrivateLessons")
                        .HasForeignKey("PrivateCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.PrivateModule", "PrivateModule")
                        .WithMany("PrivateLessons")
                        .HasForeignKey("PrivateModuleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PrivateCourse");

                    b.Navigation("PrivateModule");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PrivateModule", b =>
                {
                    b.HasOne("Edu.Domain.Entities.PrivateCourse", "PrivateCourse")
                        .WithMany("PrivateModules")
                        .HasForeignKey("PrivateCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateCourse");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PurchaseRequest", b =>
                {
                    b.HasOne("Edu.Domain.Entities.PrivateCourse", "PrivateCourse")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("PrivateCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.Student", "Student")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("StudentId");

                    b.Navigation("PrivateCourse");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveCourse", b =>
                {
                    b.HasOne("Edu.Domain.Entities.Teacher", "Teacher")
                        .WithMany("ReactiveCourses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveCourseLesson", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ReactiveCourseMonth", "ReactiveCourseMonth")
                        .WithMany("Lessons")
                        .HasForeignKey("ReactiveCourseMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReactiveCourseMonth");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveCourseMonth", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ReactiveCourse", "ReactiveCourse")
                        .WithMany("Months")
                        .HasForeignKey("ReactiveCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReactiveCourse");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveEnrollment", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ReactiveCourse", "ReactiveCourse")
                        .WithMany("Enrollments")
                        .HasForeignKey("ReactiveCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.Student", "Student")
                        .WithMany("ReactiveEnrollments")
                        .HasForeignKey("StudentId");

                    b.Navigation("ReactiveCourse");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveEnrollmentMonthPayment", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ReactiveCourseMonth", "ReactiveCourseMonth")
                        .WithMany("MonthPayments")
                        .HasForeignKey("ReactiveCourseMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.ReactiveEnrollment", "ReactiveEnrollment")
                        .WithMany("MonthPayments")
                        .HasForeignKey("ReactiveEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReactiveCourseMonth");

                    b.Navigation("ReactiveEnrollment");
                });

            modelBuilder.Entity("Edu.Domain.Entities.SchoolLesson", b =>
                {
                    b.HasOne("Edu.Domain.Entities.Curriculum", "Curriculum")
                        .WithMany("SchoolLessons")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.SchoolModule", "SchoolModule")
                        .WithMany("SchoolLessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Curriculum");

                    b.Navigation("SchoolModule");
                });

            modelBuilder.Entity("Edu.Domain.Entities.SchoolModule", b =>
                {
                    b.HasOne("Edu.Domain.Entities.Curriculum", "Curriculum")
                        .WithMany("SchoolModules")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Slot", b =>
                {
                    b.HasOne("Edu.Domain.Entities.Teacher", null)
                        .WithMany("Slots")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Student", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ApplicationUser", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Edu.Domain.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Edu.Domain.Entities.StudentCurriculum", b =>
                {
                    b.HasOne("Edu.Domain.Entities.Curriculum", "Curriculum")
                        .WithMany("StudentCurricula")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.Student", "Student")
                        .WithMany("StudentCurricula")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ApplicationUser", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("Edu.Domain.Entities.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edu.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Edu.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Edu.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Category", b =>
                {
                    b.Navigation("PrivateCourses");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Curriculum", b =>
                {
                    b.Navigation("SchoolLessons");

                    b.Navigation("SchoolModules");

                    b.Navigation("StudentCurricula");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HomeSection", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Edu.Domain.Entities.HomeSectionItem", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Level", b =>
                {
                    b.Navigation("Curricula");

                    b.Navigation("OnlineCourses");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineCourse", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");

                    b.Navigation("Months");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineCourseLesson", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineCourseMonth", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("MonthPayments");
                });

            modelBuilder.Entity("Edu.Domain.Entities.OnlineEnrollment", b =>
                {
                    b.Navigation("MonthPayments");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PrivateCourse", b =>
                {
                    b.Navigation("PrivateLessons");

                    b.Navigation("PrivateModules");

                    b.Navigation("PurchaseRequests");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PrivateLesson", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Edu.Domain.Entities.PrivateModule", b =>
                {
                    b.Navigation("PrivateLessons");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveCourse", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Months");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveCourseLesson", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveCourseMonth", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("MonthPayments");
                });

            modelBuilder.Entity("Edu.Domain.Entities.ReactiveEnrollment", b =>
                {
                    b.Navigation("MonthPayments");
                });

            modelBuilder.Entity("Edu.Domain.Entities.SchoolLesson", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Edu.Domain.Entities.SchoolModule", b =>
                {
                    b.Navigation("SchoolLessons");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Slot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Student", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("ReactiveEnrollments");

                    b.Navigation("StudentCurricula");
                });

            modelBuilder.Entity("Edu.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PrivateCourses");

                    b.Navigation("ReactiveCourses");

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
